/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package akka.actors.greeter;

import akka.actor.typed.ActorSystem;

import java.io.IOException;
public class Main {
  public static void main(String[] args) {
    final ActorSystem<GreeterMain.Start> greeterMain = ActorSystem.create(GreeterMain.create(), "helloakka");

    greeterMain.tell(new GreeterMain.Start("Charles"));

    try {
      System.out.println(">>> Press ENTER to exit <<<");
      System.in.read();
    } catch (IOException ignored) {
    } finally {
      greeterMain.terminate();
    }
  }
}